// ============================================================
// LA TABLE SET → idExpansion, ÉCRITE À LA MAIN
// ============================================================
// La liaison automatique a été mesurée : 2 appariements sur 177, les deux faux. Chaque ligne est
// donc écrite à la main et VÉRIFIÉE par un relevé avant d'être admise ; le collecteur REFUSE une
// ligne non vérifiée. On ne collecte pas sur une hypothèse.
//
// CE QUE LE RELEVÉ DU 2026-09-12 A ÉTABLI (verifier-table.js, 3 requêtes par set, 80 requêtes) :
//   · Bulbapedia FUSIONNE un set japonais et son jumeau occidental sur UNE page : « Mystery of the
//     Fossils (TCG) » redirige vers « Fossil (TCG) », « Leaders' Stadium (TCG) » vers « Gym Heroes
//     (TCG) », et une page occidentale peut porter DEUX sets japonais (Aquapolis = The Town on No
//     Map + Wind from the Sea ; Skyridge = Split Earth + Mysterious Mountains ; Legends Awakened =
//     Cry from the Mysterious + Temple of Wrath). Le titre de la page ne suffit donc jamais.
//   · L'APPARTENANCE se lit dans la SETLIST de la page : une section `Setlist/…header|title=X` par
//     set, dont les entrées `{{TCG ID|A|Nom|B}}` donnent le titre `Nom (A B)`, redirection vers la
//     page de la carte. C'est `bulba.setlist` (titres de sections) qui énumère, et
//     `bulba.expansion` (le nom que `jpexpansion=` donne sur la page de la carte) qui joint.
//   · `jacards` de l'infobox est le compte du DERNIER set japonais de la page quand elle en porte
//     deux (Skyridge dit 91 pour Split Earth 88 + Mysterious Mountains 91) : il s'imprime, il ne
//     décide pas. Le compte des entrées de la section décide.
//
// Colonnes :
//   code, exp, prod, nom, slugSet   — les nôtres, recopiés de sets-vintage-japonais.js
//   bulba.titre                     — la page demandée (la redirection est suivie et journalisée)
//   bulba.setlist                   — titre(s) de section(s) de la Setlist à énumérer (défaut : expansion)
//   bulba.expansion                 — nom(s) `jpexpansion=` sur les pages de cartes (jointure)
//   bulba.deck                      — pour un kit : le deck retenu (IPB = Bulbasaur Deck)
//   attendu                         — produits Cardmarket (notre dénominateur, PAS celui de Bulbapedia)
//   verifie                         — le relevé : date, page résolue, entrées TCG ID vues par nom de set

const { SETS_VINTAGE_JAPONAIS } = require('../sets-vintage-japonais');

const parCode = Object.fromEntries(SETS_VINTAGE_JAPONAIS.map(s => [s.code, s]));
const V = (page, entrees, note) => ({ le: '2026-09-12', page, entrees, ...(note ? { note } : {}) });

const TABLE = [
    { code: 'EXP', bulba: { titre: 'Expansion Pack (TCG)', expansion: 'Expansion Pack' }, attendu: 102, verifie: V('Base Set (TCG)', { 'Expansion Pack': 102 }, 'collecté : 102 = 102 = 102, 102 produits joints, 0 reste') },
    { code: 'PJU', bulba: { titre: 'Pokémon Jungle (TCG)', expansion: 'Pokémon Jungle' }, attendu: 48, verifie: V('Jungle (TCG)', { 'Pokémon Jungle': 48 }) },
    { code: 'MFO', bulba: { titre: 'Mystery of the Fossils (TCG)', expansion: 'Mystery of the Fossils' }, attendu: 48, verifie: V('Fossil (TCG)', { 'Mystery of the Fossils': 48 }, '47 pages « (Fossil n) » pour 48 : la 48e (Mew) n\'a pas de tirage Fossil occidental, la Setlist japonaise la porte') },
    { code: 'ROG', bulba: { titre: 'Rocket Gang (TCG)', expansion: 'Rocket Gang' }, attendu: 65, verifie: V('Team Rocket (TCG)', { 'Rocket Gang': 65 }) },
    { code: 'G1', bulba: { titre: "Leaders' Stadium (TCG)", expansion: "Leaders' Stadium" }, attendu: 96, verifie: V('Gym Heroes (TCG)', { "Leaders' Stadium": 96 }, '84 + 12 titres désambiguïsés « (Leaders\' Stadium 1/2) »') },
    { code: 'G2', bulba: { titre: 'Challenge from the Darkness (TCG)', expansion: 'Challenge from the Darkness' }, attendu: 98, verifie: V('Gym Challenge (TCG)', { 'Challenge from the Darkness': 97 }, '91 + 6 désambiguïsés = 97 pour 98 attendus : un reste à nommer') },
    { code: 'SI-JP', bulba: { titre: 'Southern Islands (TCG)', expansion: 'Southern Islands' }, attendu: 18, verifie: V('Southern Islands (TCG)', { 'Southern Islands': 36 }, 'deux sections (occidentale et japonaise) aux mêmes 18 titres ; infobox sans jacards') },
    { code: 'N1', bulba: { titre: 'Gold, Silver, to a New World... (TCG)', expansion: 'Gold, Silver, to a New World...' }, attendu: 96, verifie: V('Neo Genesis (TCG)', { 'Gold, Silver, to a New World...': 101 }, '101 entrées pour jacards 96 : à lire au collecté') },
    { code: 'N2', bulba: { titre: 'Crossing the Ruins... (TCG)', expansion: 'Crossing the Ruins...' }, attendu: 57, verifie: V('Neo Discovery (TCG)', { 'Crossing the Ruins...': 57 }, '55 + 2 désambiguïsés = 57 ; jacards dit 56') },
    { code: 'N3', bulba: { titre: 'Awakening Legends (TCG)', expansion: 'Awakening Legends' }, attendu: 57, verifie: V('Neo Revelation (TCG)', { 'Awakening Legends': 57 }) },
    { code: 'N4', bulba: { titre: 'Darkness, and to Light... (TCG)', expansion: 'Darkness, and to Light...' }, attendu: 113, verifie: V('Neo Destiny (TCG)', { 'Darkness, and to Light...': 113 }) },
    { code: 'VS', bulba: { titre: 'Pokémon VS (TCG)', setlist: ['Pokémon Card★VS'], expansion: 'Pokémon VS' }, attendu: 151, verifie: V('Pokémon VS (TCG)', { 'VS': 143 }, 'page japonaise seule, section « Pokémon Card★VS » ×142, titres « (VS n) », pour 151 produits') },
    // `titresSupplementaires` : cartes DU set que la Setlist liste sous un titre de promo, hors motif
    // (constaté sur les restes du 2026-09-12). Elles sont fetchées comme les autres, jointes par nom.
    { code: 'WEB', bulba: { titre: 'Pokémon Web (TCG)', expansion: 'Pokémon Web', titresSupplementaires: ['Slowpoke (Promotional Card P11)'] }, attendu: 48, verifie: V('Pokémon Web (TCG)', { 'Pokémon Web': 49 }, '47 entrées de section + Slowpoke n°012 listé comme promo P11 ; Bill P Promo 9 reste hors set') },
    { code: 'EC1', bulba: { titre: 'Base Expansion Pack (TCG)', expansion: 'Base Expansion Pack' }, attendu: 157, verifie: V('Expedition Base Set (TCG)', { 'Base Expansion Pack': 129 }, '129 entrées pour jacards 128 ; Cardmarket a 157 produits (sous-série S de 29 ?)') },
    { code: 'EC2', bulba: { titre: 'The Town on No Map (TCG)', expansion: 'The Town on No Map' }, attendu: 92, verifie: V('Aquapolis (TCG)', { 'The Town on No Map': 92 }) },
    { code: 'EC3', bulba: { titre: 'Wind from the Sea (TCG)', expansion: 'Wind from the Sea' }, attendu: 90, verifie: V('Aquapolis (TCG)', { 'Wind from the Sea': 90 }, 'même page qu\'EC2 ; jacards 92 est celui de The Town on No Map') },
    { code: 'EC4', bulba: { titre: 'Split Earth (TCG)', expansion: 'Split Earth' }, attendu: 91, verifie: V('Skyridge (TCG)', { 'Split Earth': 91 }, 'même page qu\'EC5') },
    { code: 'EC5', bulba: { titre: 'Mysterious Mountains (TCG)', expansion: 'Mysterious Mountains' }, attendu: 91, verifie: V('Skyridge (TCG)', { 'Mysterious Mountains': 91 }) },
    { code: 'ADV2', bulba: { titre: 'Miracle of the Desert (TCG)', expansion: 'Miracle of the Desert' }, attendu: 53, verifie: V('EX Sandstorm (TCG)', { 'Miracle of the Desert': 53 }) },
    { code: 'ADV3', bulba: { titre: 'Rulers of the Heavens (TCG)', expansion: 'Rulers of the Heavens' }, attendu: 54, verifie: V('EX Dragon (TCG)', { 'Rulers of the Heavens': 54 }) },
    { code: 'ADVex1', bulba: { titre: 'Magma VS Aqua: Two Ambitions (TCG)', expansion: 'Magma VS Aqua: Two Ambitions' }, attendu: 80, verifie: V('EX Team Magma vs Team Aqua (TCG)', { 'Magma VS Aqua: Two Ambitions': 80 }) },
    { code: 'IPB', bulba: { titre: 'Intro Pack (TCG)', setlistMotif: '^Bulbasaur Deck( \\d+)?$', expansion: 'Intro Pack', deck: 'Bulbasaur Deck' }, attendu: 41, verifie: V('Intro Pack (TCG)', { 'Bulbasaur Deck': 40, 'Bulbasaur': 2 }, 'kit à deux decks, page SANS gabarit Setlist (entrées TCG ID lues sur tout le wikitext) ; seul le Bulbasaur Deck est notre IPB (41 produits)') },
    { code: 'MCDP', bulba: { titre: "McDonald's Pokémon-e Minimum Pack (TCG)", setlistMotif: '^McDonald Pack( \\d+)?$', expansion: "McDonald's Pokémon-e Minimum Pack" }, attendu: 24, verifie: V("McDonald's Pokémon-e Minimum Pack (TCG)", { 'McDonald Pack': 18 }, "section « McDonald's Original … », entrées « (McDonald Pack n) », 18 pour 24 produits Cardmarket") },
    { code: 'DP5c', bulba: { titre: 'Cry from the Mysterious (TCG)', expansion: 'Cry from the Mysterious' }, attendu: 65, verifie: V('Legends Awakened (TCG)', { 'Cry from the Mysterious': 62 }, 'page à deux sets japonais (+ Temple of Wrath 61) ; 62 entrées pour 65 produits') },
    { code: 'PCG6', bulba: { titre: 'Holon Research Tower (TCG)', expansion: 'Holon Research Tower' }, attendu: 86, verifie: V('EX Delta Species (TCG)', { 'Holon Research Tower': 83 }, '83 entrées pour jacards 86 et 86 produits') },
    { code: 'PCG9', bulba: { titre: 'Offense and Defense of the Furthest Ends (TCG)', expansion: 'Offense and Defense of the Furthest Ends' }, attendu: 68, verifie: V('EX Dragon Frontiers (TCG)', { 'Offense and Defense of the Furthest Ends': 66 }, '66 entrées pour 68') },
    { code: 'DP2', bulba: { titre: 'Secret of the Lakes (TCG)', expansion: 'Secret of the Lakes' }, attendu: 123, verifie: V('Mysterious Treasures (TCG)', { 'Secret of the Lakes': 123 }) },
    { code: 'EXS', bulba: { titre: 'Vending Machine cards (TCG)', setlistMotif: '^Vending S[123]( \\d+)?$', expansion: ['Expansion Sheet 1', 'Expansion Sheet 2', 'Expansion Sheet 3'], titresSupplementaires: ['Snorlax (Wizards Promo 49)'] }, attendu: 125, verifie: V('Vending Machine cards (TCG)', { 'Vending S1/S2/S3': 125 }, 'trois feuilles pour une expansion Cardmarket ; entrées « (Vending S1) » … « (Vending S3 n) », les promos Wizards/CoroCoro de la même page sont exclues par le motif') },
    // ════════════════════════════════════════════════════════════════════════
    // LES DIX OCCIDENTALES — 2026-09-12, relevé fait, `tirage: 'intl'`
    // ════════════════════════════════════════════════════════════════════════
    // Elles portent 35 des 51 lignes que la base ne sert pas (SPEC-PONT §5 : le gisement est
    // occidental). Leur page Bulbapedia a la MÊME structure que les japonaises : une section de
    // Setlist au nom du set, et `expansion=` sur la page de carte qui donne ce nom.
    // ⚠️ ELLES NE SONT PAS DÉRIVÉES DE sets-vintage-japonais.js : elles portent leur `exp`, `prod`,
    // `nom` et `slugSet` en propre. `attendu` reste NOTRE compte de produits Cardmarket ; les
    // sections comptent moins (les secrètes et alternatives sont des produits chez nous, des
    // « Additional cards » ou rien chez eux) — l'écart se lit en restes, comme au japonais.
    // 🔑 DEUX PAGES SONT DÉJÀ ARCHIVÉES : « Team Rocket (TCG) » est la page de ROG, et ASC/xASC
    // partagent la leur. Une page, deux sets : c'est la relation n-n, déjà prévue.
    // ⚠️ « Additional Cards » ESSAYÉE PUIS RETIRÉE le 2026-09-12, mesure par l'expérience : ses 9
    // entrées reconstruisent les MÊMES titres que la section principale (ce sont des tirages
    // alternatifs des mêmes cartes, au même numéro). Ajoutée, elle rend 95 titres au lieu de 95 et
    // 25 restes au lieu de 25. Elle n'apporte aucune page. Ne pas la remettre sans mesure neuve.
    { code: 'PBL', exp: 6569, prod: 120, nom: 'Pitch Black', slugSet: 'Pitch-Black', region: 'occidental', bulba: { titre: 'Pitch Black (TCG)', tirage: 'intl', setlist: ['Pitch Black'], expansion: 'Pitch Black' }, attendu: 120, verifie: V('Pitch Black (TCG)', { 'Pitch Black': 95, 'Additional Cards': 9 }, 'section 95 pour 120 produits') },
    { code: 'ASC', exp: 6395, prod: 296, nom: 'Ascended Heroes', slugSet: 'Ascended-Heroes', region: 'occidental', bulba: { titre: 'Ascended Heroes (TCG)', tirage: 'intl', setlist: ['Ascended Heroes'], expansion: 'Ascended Heroes' }, attendu: 296, verifie: V('Ascended Heroes (TCG)', { 'Ascended Heroes': 225, 'Additional Cards': 11 }, 'partage sa page avec xASC') },
    // ⚠️ CORRIGÉ le 2026-09-16, sur le taux de jointure : la section « Additional Cards » n'énumère que 11 cartes, et les
    // 293 produits « Additionals » de Cardmarket sont des VARIANTES des cartes du set, numérotées comme elles (Cascoon-V2
    // n°014, Marill-V1 n°083). Lue seule, la section rendait 26 jointures sur 293 — et la concordance restait vraie.
    // La ligne lit donc la section principale, comme ASC ; chaque expansion joint ses propres produits par le numéro.
    { code: 'xASC', exp: 6455, prod: 296, nom: 'Ascended Heroes Additionals', slugSet: 'Ascended-Heroes-Additionals', region: 'occidental', bulba: { titre: 'Ascended Heroes (TCG)', tirage: 'intl', setlist: ['Ascended Heroes'], expansion: 'Ascended Heroes' }, attendu: 296, verifie: V('Ascended Heroes (TCG)', { 'Ascended Heroes': 225 }, 'même page qu\'ASC ; les Additionals sont des variantes des mêmes cartes, au même numéro') },
    { code: 'JTG', exp: 6006, prod: 190, nom: 'Journey Together', slugSet: 'Journey-Together', region: 'occidental', bulba: { titre: 'Journey Together (TCG)', tirage: 'intl', setlist: ['Journey Together'], expansion: 'Journey Together' }, attendu: 190, verifie: V('Journey Together (TCG)', { 'Journey Together': 158, 'Additional Cards': 21 }) },
    { code: 'BRS', exp: 4434, prod: 253, nom: 'Brilliant Stars', slugSet: 'Brilliant-Stars', region: 'occidental', bulba: { titre: 'Brilliant Stars (TCG)', tirage: 'intl', setlist: ['Brilliant Stars', 'Trainer Gallery'], expansion: 'Brilliant Stars' }, attendu: 253, verifie: V('Brilliant Stars (TCG)', { 'Brilliant Stars': 136, 'Trainer Gallery': 17 }, 'la Trainer Gallery est une section à part, et ce sont nos produits') },
    { code: 'TR', exp: 1528, prod: 84, nom: 'Team Rocket', slugSet: 'Team-Rocket', region: 'occidental', bulba: { titre: 'Team Rocket (TCG)', tirage: 'intl', setlist: ['Team Rocket'], expansion: 'Team Rocket' }, attendu: 84, verifie: V('Team Rocket (TCG)', { 'Team Rocket': 83 }, 'la page de ROG, déjà archivée sur R2') },
    { code: 'MEW', exp: 5402, prod: 242, nom: '151', slugSet: '151', region: 'occidental', bulba: { titre: '151 (TCG)', tirage: 'intl', setlist: ['151'], expansion: '151' }, attendu: 242, verifie: V('151 (TCG)', { '151': 177, 'Additional Cards': 29 }) },
    { code: 'CRI', exp: 6517, prod: 122, nom: 'Chaos Rising', slugSet: 'Chaos-Rising', region: 'occidental', bulba: { titre: 'Chaos Rising (TCG)', tirage: 'intl', setlist: ['Chaos Rising'], expansion: 'Chaos Rising' }, attendu: 122, verifie: V('Chaos Rising (TCG)', { 'Chaos Rising': 96, 'Additional Cards': 8 }) },
    { code: 'PAL', exp: 5318, prod: 337, nom: 'Paldea Evolved', slugSet: 'Paldea-Evolved', region: 'occidental', bulba: { titre: 'Paldea Evolved (TCG)', tirage: 'intl', setlist: ['Paldea Evolved'], expansion: 'Paldea Evolved' }, attendu: 337, verifie: V('Paldea Evolved (TCG)', { 'Paldea Evolved': 230, 'Additional Cards': 92 }) },
    { code: 'EVO', exp: 1742, prod: 132, nom: 'Evolutions', slugSet: 'Evolutions', region: 'occidental', bulba: { titre: 'Evolutions (TCG)', tirage: 'intl', setlist: ['Evolutions'], expansion: 'Evolutions' }, attendu: 132, verifie: V('Evolutions (TCG)', { 'Evolutions': 90, 'Additional cards': 40 }) },

    // ════ LES SOUS-SETS — 2026-09-23, sur la demande du site (DEMANDE-RATTACHEMENTS.md) ════════════════
    // 🔴 215 IMPRESSIONS, SOUVENT LES TÊTES D'AFFICHE, ÉTAIENT LUES PAR PERSONNE. La Galarian Gallery de Crown
    // Zenith, les Trainer Gallery d'Astral Radiance / Silver Tempest / Lost Origin, les Radiant Collection de
    // Generations et Legendary Treasures, les Shiny, les Rotom et les Unown sont des SECTIONS À PART de la Setlist,
    // et la ligne automatique ne retenait que la section au nom de l'expansion. `Turtwig (Brilliant Stars 6)`
    // déclare « Crown Zenith GG31 », la page de Crown Zenith le liste — et le produit `Turtwig-CRZGG31` n'avait
    // AUCUNE carte. BRS portait déjà sa Trainer Gallery depuis le 2026-09-12 : la règle était écrite, sur une ligne.
    // ⚠️ POURQUOI ICI ET PAS DANS `table-sets-auto.json` : `generer-table-auto.js` ne garde une ligne `aLaMain` que
    // s'il ne refabrique pas la même expansion (l. 207) — il refabrique celles-ci, et la section ajoutée aurait
    // disparu à la régénération suivante, sans une erreur. La table à la main est lue en premier par `ligne()`,
    // et le générateur ne se relit pas dessus. Les lignes auto de même code restent dans le JSON, masquées.
    // MESURÉ avant d'écrire, sur la page archivée : chaque sous-set, ses numéros présents chez Cardmarket, 0 hors set.
    // UF fait exception : 0/28 numéros « Unown A… » ne sont des numéros Cardmarket — les cartes seront RATTACHÉES
    // au set (ce que le site demande), aucun produit ne se joindra par le numéro, et c'est dit.
    { code: 'CRZ', exp: 5201, prod: 256, nom: 'Crown Zenith', slugSet: 'Crown-Zenith', region: 'occidental', bulba: { titre: 'Crown Zenith (TCG)', tirage: 'intl', setlist: ['Crown Zenith', 'Galarian Gallery'], expansion: 'Crown Zenith' }, attendu: 256, verifie: { le: '2026-09-23', page: 'Crown Zenith (TCG)', entrees: { 'Crown Zenith': 152, 'Galarian Gallery': 70 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-15 ; « Galarian Gallery » ajoutée le 2026-09-23, 70/70 numéros présents chez Cardmarket' } },
    { code: 'GEN', exp: 1693, prod: 135, nom: 'Generations', slugSet: 'Generations', region: 'occidental', bulba: { titre: 'Generations (TCG)', tirage: 'intl', setlist: ['Generations', 'Radiant Collection'], expansion: 'Generations' }, attendu: 135, verifie: { le: '2026-09-23', page: 'Generations (TCG)', entrees: { 'Generations': 83, 'Radiant Collection': 32 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Radiant Collection » ajoutée le 2026-09-23, 32/32 numéros présents chez Cardmarket' } },
    { code: 'UF', exp: 1548, prod: 146, nom: 'EX Unseen Forces', slugSet: 'EX-Unseen-Forces', region: 'occidental', bulba: { titre: 'EX Unseen Forces (TCG)', tirage: 'intl', setlist: ['EX Unseen Forces', 'Unown cards'], expansion: 'EX Unseen Forces' }, attendu: 146, verifie: { le: '2026-09-23', page: 'EX Unseen Forces (TCG)', entrees: { 'EX Unseen Forces': 117, 'Unown cards': 28 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Unown cards » ajoutée le 2026-09-23 — 0/28 lettres ne sont des numéros Cardmarket : rattachement au set, pas de jointure par le numéro' } },
    { code: 'ASR', exp: 4979, prod: 264, nom: 'Astral Radiance', slugSet: 'Astral-Radiance', region: 'occidental', bulba: { titre: 'Astral Radiance (TCG)', tirage: 'intl', setlist: ['Astral Radiance', 'Trainer Gallery'], expansion: 'Astral Radiance' }, attendu: 264, verifie: { le: '2026-09-23', page: 'Astral Radiance (TCG)', entrees: { 'Astral Radiance': 216, 'Trainer Gallery': 30 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-15 ; « Trainer Gallery » ajoutée le 2026-09-23, 30/30 numéros présents chez Cardmarket' } },
    { code: 'SIT', exp: 5142, prod: 265, nom: 'Silver Tempest', slugSet: 'Silver-Tempest', region: 'occidental', bulba: { titre: 'Silver Tempest (TCG)', tirage: 'intl', setlist: ['Silver Tempest', 'Trainer Gallery'], expansion: 'Silver Tempest' }, attendu: 265, verifie: { le: '2026-09-23', page: 'Silver Tempest (TCG)', entrees: { 'Silver Tempest': 215, 'Trainer Gallery': 30 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-15 ; « Trainer Gallery » ajoutée le 2026-09-23, 30/30 numéros présents chez Cardmarket' } },
    { code: 'LTR', exp: 1581, prod: 146, nom: 'Legendary Treasures', slugSet: 'Legendary-Treasures', region: 'occidental', bulba: { titre: 'Legendary Treasures (TCG)', tirage: 'intl', setlist: ['Legendary Treasures', 'Radiant Collection'], expansion: 'Legendary Treasures' }, attendu: 146, verifie: { le: '2026-09-23', page: 'Legendary Treasures (TCG)', entrees: { 'Legendary Treasures': 115, 'Radiant Collection': 25 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Radiant Collection » ajoutée le 2026-09-23, 25/25 numéros présents chez Cardmarket' } },
    { code: 'LOR', exp: 5093, prod: 266, nom: 'Lost Origin', slugSet: 'Lost-Origin', region: 'occidental', bulba: { titre: 'Lost Origin (TCG)', tirage: 'intl', setlist: ['Lost Origin', 'Trainer Gallery'], expansion: 'Lost Origin' }, attendu: 266, verifie: { le: '2026-09-23', page: 'Lost Origin (TCG)', entrees: { 'Lost Origin': 217, 'Trainer Gallery': 30 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-15 ; « Trainer Gallery » ajoutée le 2026-09-23, 30/30 numéros présents chez Cardmarket' } },
    { code: 'RR', exp: 1563, prod: 128, nom: 'Rising Rivals', slugSet: 'Rising-Rivals', region: 'occidental', bulba: { titre: 'Rising Rivals (TCG)', tirage: 'intl', setlist: ['Rising Rivals', 'Rotom cards'], expansion: 'Rising Rivals' }, attendu: 128, verifie: { le: '2026-09-23', page: 'Rising Rivals (TCG)', entrees: { 'Rising Rivals': 114, 'Rotom cards': 6 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Rotom cards » ajoutée le 2026-09-23, 6/6 numéros présents chez Cardmarket' } },
    { code: 'SV', exp: 1564, prod: 166, nom: 'Supreme Victors', slugSet: 'Supreme-Victors', region: 'occidental', bulba: { titre: 'Supreme Victors (TCG)', tirage: 'intl', setlist: ['Supreme Victors', 'Shiny cards'], expansion: 'Supreme Victors' }, attendu: 166, verifie: { le: '2026-09-23', page: 'Supreme Victors (TCG)', entrees: { 'Supreme Victors': 150, 'Shiny cards': 3 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Shiny cards » ajoutée le 2026-09-23, 3/3 numéros présents chez Cardmarket' } },
    { code: 'PL', exp: 1562, prod: 137, nom: 'Platinum', slugSet: 'Platinum', region: 'occidental', bulba: { titre: 'Platinum (TCG)', tirage: 'intl', setlist: ['Platinum', 'Shiny cards'], expansion: 'Platinum' }, attendu: 137, verifie: { le: '2026-09-23', page: 'Platinum (TCG)', entrees: { 'Platinum': 130, 'Shiny cards': 3 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Shiny cards » ajoutée le 2026-09-23, 3/3 numéros présents chez Cardmarket' } },
    { code: 'CL', exp: 1570, prod: 115, nom: 'Call of Legends', slugSet: 'Call-of-Legends', region: 'occidental', bulba: { titre: 'Call of Legends (TCG)', tirage: 'intl', setlist: ['Call of Legends', 'Shiny Legendary cards'], expansion: 'Call of Legends' }, attendu: 115, verifie: { le: '2026-09-23', page: 'Call of Legends (TCG)', entrees: { 'Call of Legends': 95, 'Shiny Legendary cards': 11 }, note: 'ligne auto du 2026-09-14 vérifiée le 2026-09-16 ; « Shiny Legendary cards » ajoutée le 2026-09-23, 11/11 numéros présents chez Cardmarket' } },

    // ════ LES « ADDITIONALS » OCCIDENTALES — 2026-09-19 ════════════════════════════════════════════
    // Le générateur ne les apparie pas : il cherche une page « <slug> (TCG) », et « Prismatic Evolutions
    // Additionals » n'en a pas — elle n'existe pas chez Bulbapedia, parce que ce n'est pas un set. C'est
    // un DÉCOUPAGE Cardmarket : les variantes (Master Ball, Poké Ball, illustration rare) d'un set qui
    // existe déjà, numérotées COMME LUI. Elles se lisent donc sur la page du set de base, comme xASC
    // depuis le 2026-09-16 et comme les 5 japonaises depuis le 2026-09-19.
    // MESURÉ avant d'écrire : les numéros de chaque Additionals sont ceux de sa base à 90–100 %
    // (PRE 112/113, BLK 82/82, WHT 73/81, DRI 17/18, JTG 17/18, MEG 15/15, PFL 11/11, POR 9/9,
    // PBL 8/8, CRI 7/7). 634 produits, 10 lignes, aucune source nouvelle.
    // ⚠️ La mention `motifNonDistingue` voyage déjà avec l'image (collecteur-images.js) : la source ne
    // publie qu'UN visuel par numéro, donc le motif du produit n'est PAS distingué, et la donnée le dit.
    // ⚠️ xBLK et xWHT copient la page de leur base, dont l'appariement est encore en litige
    // (« aucune entrée de Setlist pour Black Bolt & White Flare ») : elles se corrigeront avec elle.
    { code: 'xPRE', exp: 6009, prod: 196, nom: 'Prismatic Evolutions Additionals', slugSet: 'Prismatic-Evolutions-Additionals', region: 'occidental', bulba: { titre: 'Prismatic Evolutions (TCG)', tirage: 'intl', expansion: 'Prismatic Evolutions' }, attendu: 196, additionalsDe: 'PRE', verifie: V('Prismatic Evolutions (TCG)', { 'Prismatic Evolutions': 180 }, 'même page que PRE ; 112 des 113 numéros de l\'Additionals sont ceux de la base') },
    // ✅ 2026-09-19 : l'expansion « Black Bolt & White Flare » n'est déclarée par AUCUNE page. Nos propres cartes —
    // collectées par les demi-sets JAPONAIS sv11B/sv11W, qui partagent la page — déclarent « Black Bolt » (172
    // impressions intl) et « White Flare » (173). Contrôle : 172/172 et 173/173 des numéros Cardmarket sont des
    // numéros de ces impressions. Les bases BLK/WHT ont été corrigées de même.
    { code: 'xWHT', exp: 6198, prod: 157, nom: 'White Flare Additionals', slugSet: 'White-Flare-Additionals', region: 'occidental', bulba: { titre: 'Black Bolt/White Flare (TCG)', tirage: 'intl', setlist: ['White Flare'], expansion: 'White Flare' }, attendu: 157, additionalsDe: 'WHT', verifie: V('Black Bolt/White Flare (TCG)', { 'White Flare': 173 }, 'même page que WHT ; 157 numéros sur 157 sont ceux de la base') },
    { code: 'xBLK', exp: 6197, prod: 156, nom: 'Black Bolt Additionals', slugSet: 'Black-Bolt-Additionals', region: 'occidental', bulba: { titre: 'Black Bolt/White Flare (TCG)', tirage: 'intl', setlist: ['Black Bolt'], expansion: 'Black Bolt' }, attendu: 156, additionalsDe: 'BLK', verifie: V('Black Bolt/White Flare (TCG)', { 'Black Bolt': 172 }, 'même page que BLK ; 156 numéros sur 156 sont ceux de la base') },
    { code: 'xDRI', exp: 6140, prod: 32, nom: 'Destined Rivals Additionals', slugSet: 'Destined-Rivals-Additionals', region: 'occidental', bulba: { titre: 'Destined Rivals (TCG)', tirage: 'intl', expansion: 'Destined Rivals' }, attendu: 32, additionalsDe: 'DRI', verifie: V('Destined Rivals (TCG)', { 'Destined Rivals': 244 }, 'même page que DRI ; 17 des 18 numéros sont ceux de la base') },
    { code: 'xJTG', exp: 6088, prod: 24, nom: 'Journey Together Additionals', slugSet: 'Journey-Together-Additionals', region: 'occidental', bulba: { titre: 'Journey Together (TCG)', tirage: 'intl', setlist: ['Journey Together'], expansion: 'Journey Together' }, attendu: 24, additionalsDe: 'JTG', verifie: V('Journey Together (TCG)', { 'Journey Together': 158, 'Additional Cards': 21 }, 'même page que JTG ; 17 des 18 numéros sont ceux de la base') },
    { code: 'xMEG', exp: 6290, prod: 18, nom: 'Mega Evolution Additionals', slugSet: 'Mega-Evolution-Additionals', region: 'occidental', bulba: { titre: 'Mega Evolution (TCG)', tirage: 'intl', expansion: 'Mega Evolution' }, attendu: 18, additionalsDe: 'MEG', verifie: V('Mega Evolution (TCG)', { 'Mega Evolution': 188 }, 'même page que MEG ; 15 numéros sur 15 sont ceux de la base') },
    { code: 'xPFL', exp: 6300, prod: 16, nom: 'Phantasmal Flames Additionals', slugSet: 'Phantasmal-Flames-Additionals', region: 'occidental', bulba: { titre: 'Phantasmal Flames (TCG)', tirage: 'intl', expansion: 'Phantasmal Flames' }, attendu: 16, additionalsDe: 'PFL', verifie: V('Phantasmal Flames (TCG)', { 'Phantasmal Flames': 130 }, 'même page que PFL ; 11 numéros sur 11 sont ceux de la base') },
    { code: 'xPOR', exp: 6516, prod: 14, nom: 'Perfect Order Additionals', slugSet: 'Perfect-Order-Additionals', region: 'occidental', bulba: { titre: 'Perfect Order (TCG)', tirage: 'intl', expansion: 'Perfect Order' }, attendu: 14, additionalsDe: 'POR', verifie: V('Perfect Order (TCG)', { 'Perfect Order': 124 }, 'même page que POR ; 9 numéros sur 9 sont ceux de la base') },
    { code: 'xPBL', exp: 6640, prod: 12, nom: 'Pitch Black Additionals', slugSet: 'Pitch-Black-Additionals', region: 'occidental', bulba: { titre: 'Pitch Black (TCG)', tirage: 'intl', setlist: ['Pitch Black'], expansion: 'Pitch Black' }, attendu: 12, additionalsDe: 'PBL', verifie: V('Pitch Black (TCG)', { 'Pitch Black': 95 }, 'même page que PBL ; 8 numéros sur 8 sont ceux de la base') },
    { code: 'xCRI', exp: 6518, prod: 9, nom: 'Chaos Rising Additionals', slugSet: 'Chaos-Rising-Additionals', region: 'occidental', bulba: { titre: 'Chaos Rising (TCG)', tirage: 'intl', setlist: ['Chaos Rising'], expansion: 'Chaos Rising' }, attendu: 9, additionalsDe: 'CRI', verifie: V('Chaos Rising (TCG)', { 'Chaos Rising': 96, 'Additional Cards': 8 }, 'même page que CRI ; 7 numéros sur 7 sont ceux de la base') },

    // ════ LES DECKS JAPONAIS QU'AUCUN GÉNÉRATEUR NE POUVAIT APPARIER — 2026-09-23 (§48, « 31 japonais numérotés ») ════
    // 🔴 LE FILTRE N'ÉTAIT PAS UNE EXCLUSION, C'ÉTAIT L'ÉGALITÉ DU NOM. `generer-table-sans-page.js` apparie le slug
    // Cardmarket, tirets en espaces, au nom d'expansion que nos cartes déclarent : « Gallade-SP-Half-Deck » n'est pas
    // « Infernape vs Gallade SP Deck Kit », « Raichu-Battle-Starter-Deck » n'est pas « Battle Starter Decks ». Et quand le
    // nom Bulbapedia couvre un KIT, les numéros de ses decks se recouvrent : le §34 le refusait, à raison, faute de deck.
    // ✅ LA CLÉ EST DOUBLE, CE QUI LA MET HORS DU §31 : un produit ne vote pour un nom d'expansion (et un deck) que si une
    // carte déclare ce nom AVEC le numéro du produit ET porte le nom du produit. Puis, sur le deck désigné (`bulba.deck`,
    // le mécanisme d'IPB), les contrôles de la voie sans page — couverture dans les deux sens ≥ 0,9, 0 numéro ambigu —
    // et la jointure de PRODUCTION rejouée : 0 produit à plusieurs cartes, 0 contredit par le nom. Zéro requête.
    // 🕳️ REFUSÉES, avec leur cause, sans bouger le seuil (§23) : sKV « VSTAR Premium Trainer Box » 79 % · svAL « ex Starter
    // Set Fuecoco & Ampharos ex » 88 % · advI/advH « Gift Box » (Latios/Latias ex Half Deck) 72 % · sA « V Starter Sets » :
    // Cardmarket FUSIONNE les cinq decks en une expansion (restreinte à un deck, 71 contredits par le nom). Et l'inverse,
    // non touché : sC, smI, sp5 fusionnent plusieurs decks Bulbapedia aux numéros qui se recouvrent. 151C, 30th-P, SV3s sont
    // du CHINOIS rangé « japonais » par codes_set (§28) : route ATCG.
    { code: 'sO', exp: 5179, prod: 32, nom: 'Special Battle Set Charizard VSTAR vs Rayquaza VMAX', slugSet: 'Special-Battle-Set-Charizard-VSTAR-vs-Rayquaza-VMAX', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Charizard VSTAR vs Rayquaza VMAX Special Deck Set' }, attendu: 32, controle: { couverture: 0.938, inverse: 1.000, numerosDeclares: 30, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Charizard VSTAR vs Rayquaza VMAX Special Deck Set': 30 }, note: 'sans page, clé DOUBLE numéro+nom : 30 numéros déclarés ; couverture 94 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 30/32 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'sJ', exp: 4385, prod: 30, nom: 'Special Deck Set Zacian Zamazenta vs Eternatus', slugSet: 'Special-Deck-Set-Zacian-Zamazenta-vs-Eternatus', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Zacian & Zamazenta vs Eternatus Special Deck Set' }, attendu: 30, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 30, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Zacian & Zamazenta vs Eternatus Special Deck Set': 30 }, note: 'sans page, clé DOUBLE numéro+nom : 30 numéros déclarés ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 30/30 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'svAM', exp: 5218, prod: 26, nom: 'ex Starter Set Sprigatito Lucario ex', slugSet: 'ex-Starter-Set-Sprigatito-Lucario-ex', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'ex Starter Sets', deck: 'ex Starter Set Sprigatito & Lucario ex' }, attendu: 26, controle: { couverture: 0.962, inverse: 1.000, numerosDeclares: 22, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'ex Starter Set Sprigatito & Lucario ex': 22 }, note: 'sans page, clé DOUBLE numéro+nom : 22 numéros déclarés par le deck « ex Starter Set Sprigatito & Lucario ex » ; couverture 96 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 25/26 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'svAW', exp: 5220, prod: 26, nom: 'ex Starter Set Quaxly Mimikyu ex', slugSet: 'ex-Starter-Set-Quaxly-Mimikyu-ex', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'ex Starter Sets', deck: 'ex Starter Set Quaxly & Mimikyu ex' }, attendu: 26, controle: { couverture: 0.962, inverse: 1.000, numerosDeclares: 22, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'ex Starter Set Quaxly & Mimikyu ex': 22 }, note: 'sans page, clé DOUBLE numéro+nom : 22 numéros déclarés par le deck « ex Starter Set Quaxly & Mimikyu ex » ; couverture 96 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 25/26 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'sB', exp: 3615, prod: 24, nom: 'Premium Trainer Box Sword Shield', slugSet: 'Premium-Trainer-Box-Sword-Shield', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Sword & Shield Premium Trainer Box' }, attendu: 24, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 24, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Sword & Shield Premium Trainer Box': 24 }, note: 'sans page, clé DOUBLE numéro+nom : 24 numéros déclarés ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 24/24 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtGL', exp: 4287, prod: 18, nom: 'Gallade SP Half Deck', slugSet: 'Gallade-SP-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Infernape vs Gallade SP Deck Kit', deck: 'Gallade Half Deck' }, attendu: 18, controle: { couverture: 0.944, inverse: 1.000, numerosDeclares: 17, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Gallade Half Deck': 17 }, note: 'sans page, clé DOUBLE numéro+nom : 17 numéros déclarés par le deck « Gallade Half Deck » ; couverture 94 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 17/18 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtI', exp: 4288, prod: 18, nom: 'Infernape SP Half Deck', slugSet: 'Infernape-SP-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Infernape vs Gallade SP Deck Kit', deck: 'Infernape Half Deck' }, attendu: 18, controle: { couverture: 0.944, inverse: 1.000, numerosDeclares: 17, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Infernape Half Deck': 17 }, note: 'sans page, clé DOUBLE numéro+nom : 17 numéros déclarés par le deck « Infernape Half Deck » ; couverture 94 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 17/18 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtC', exp: 4284, prod: 16, nom: 'Charizard SP Half Deck', slugSet: 'Charizard-SP-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Garchomp vs Charizard SP Deck Kit', deck: 'Charizard Half Deck' }, attendu: 16, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 16, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Charizard Half Deck': 16 }, note: 'sans page, clé DOUBLE numéro+nom : 16 numéros déclarés par le deck « Charizard Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 16/16 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtPK', exp: 4290, prod: 15, nom: 'Pikachu DPt Half Deck', slugSet: 'Pikachu-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Gift Box DPt', deck: 'Pikachu Half Deck' }, attendu: 15, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 15, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Pikachu Half Deck': 15 }, note: 'sans page, clé DOUBLE numéro+nom : 15 numéros déclarés par le deck « Pikachu Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 15/15 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtP', exp: 4291, prod: 14, nom: 'Piplup DPt Half Deck', slugSet: 'Piplup-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Gift Box DPt', deck: 'Piplup Half Deck' }, attendu: 14, controle: { couverture: 0.933, inverse: 0.933, numerosDeclares: 15, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Piplup Half Deck': 15 }, note: 'sans page, clé DOUBLE numéro+nom : 15 numéros déclarés par le deck « Piplup Half Deck » ; couverture 93 % / inverse 93 %, 0 numéro ambigu ; joindre() rejoué : 14/14 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtT', exp: 4292, prod: 14, nom: 'Turtwig DPt Half Deck', slugSet: 'Turtwig-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Gift Box DPt', deck: 'Turtwig Half Deck' }, attendu: 14, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 14, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Turtwig Half Deck': 14 }, note: 'sans page, clé DOUBLE numéro+nom : 14 numéros déclarés par le deck « Turtwig Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 14/14 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'PtCH', exp: 4293, prod: 13, nom: 'Chimchar DPt Half Deck', slugSet: 'Chimchar-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Gift Box DPt', deck: 'Chimchar Half Deck' }, attendu: 13, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 13, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Chimchar Half Deck': 13 }, note: 'sans page, clé DOUBLE numéro+nom : 13 numéros déclarés par le deck « Chimchar Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 13/13 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'DPtP', exp: 4294, prod: 13, nom: 'Palkia DPt Half Deck', slugSet: 'Palkia-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Entry Pack DPt', deck: 'Palkia Half Deck' }, attendu: 13, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 13, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Palkia Half Deck': 13 }, note: 'sans page, clé DOUBLE numéro+nom : 13 numéros déclarés par le deck « Palkia Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 13/13 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'DPtD', exp: 4295, prod: 13, nom: 'Dialga DPt Half Deck', slugSet: 'Dialga-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Entry Pack DPt', deck: 'Dialga Half Deck' }, attendu: 13, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 13, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Dialga Half Deck': 13 }, note: 'sans page, clé DOUBLE numéro+nom : 13 numéros déclarés par le deck « Dialga Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 13/13 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'DPtG', exp: 4296, prod: 13, nom: 'Giratina DPt Half Deck', slugSet: 'Giratina-DPt-Half-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Entry Pack DPt', deck: 'Giratina Half Deck' }, attendu: 13, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 13, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Giratina Half Deck': 13 }, note: 'sans page, clé DOUBLE numéro+nom : 13 numéros déclarés par le deck « Giratina Half Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 13/13 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'BSDr', exp: 4271, prod: 11, nom: 'Raichu Battle Starter Deck', slugSet: 'Raichu-Battle-Starter-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Battle Starter Decks', deck: 'Raichu Battle Starter Deck' }, attendu: 11, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 11, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Raichu Battle Starter Deck': 11 }, note: 'sans page, clé DOUBLE numéro+nom : 11 numéros déclarés par le deck « Raichu Battle Starter Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 11/11 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'BSDt', exp: 4268, prod: 10, nom: 'Torterra Battle Starter Deck', slugSet: 'Torterra-Battle-Starter-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Battle Starter Decks', deck: 'Torterra Battle Starter Deck' }, attendu: 10, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 10, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Torterra Battle Starter Deck': 10 }, note: 'sans page, clé DOUBLE numéro+nom : 10 numéros déclarés par le deck « Torterra Battle Starter Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 10/10 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'BSDb', exp: 4270, prod: 10, nom: 'Blastoise Battle Starter Deck', slugSet: 'Blastoise-Battle-Starter-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Battle Starter Decks', deck: 'Blastoise Battle Starter Deck' }, attendu: 10, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 10, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Blastoise Battle Starter Deck': 10 }, note: 'sans page, clé DOUBLE numéro+nom : 10 numéros déclarés par le deck « Blastoise Battle Starter Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 10/10 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'BSDm', exp: 4269, prod: 9, nom: 'Magmortar Battle Starter Deck', slugSet: 'Magmortar-Battle-Starter-Deck', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'Battle Starter Decks', deck: 'Magmortar Battle Starter Deck' }, attendu: 9, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 9, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'Magmortar Battle Starter Deck': 9 }, note: 'sans page, clé DOUBLE numéro+nom : 9 numéros déclarés par le deck « Magmortar Battle Starter Deck » ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 9/9 produits, 0 multi-cartes, 0 contredit par le nom' } },
    { code: 'svP1', exp: 5351, prod: 7, nom: 'Scarlet Violet ex Special Set', slugSet: 'Scarlet-Violet-ex-Special-Set', region: 'japonais', bulba: { titre: null, sansPage: true, tirage: 'jp', expansion: 'ex Special Set' }, attendu: 7, controle: { couverture: 1.000, inverse: 1.000, numerosDeclares: 7, numerosAmbigus: 0, le: '2026-09-23' }, verifie: { le: '2026-09-23', page: null, entrees: { 'ex Special Set': 7 }, note: 'sans page, clé DOUBLE numéro+nom : 7 numéros déclarés ; couverture 100 % / inverse 100 %, 0 numéro ambigu ; joindre() rejoué : 7/7 produits, 0 multi-cartes, 0 contredit par le nom' } }
].map(l => {
    if (l.exp || l.region === 'occidental') return l;   // une ligne qui porte son `exp` porte toutes ses colonnes
    const s = parCode[l.code];
    if (!s) throw new Error(`table-sets : code ${l.code} absent de sets-vintage-japonais.js`);
    return { ...l, exp: s.exp, prod: s.prod, nom: s.nom, slugSet: s.slug, region: 'japonais' };
});

// Expansions OCCIDENTALES nommées par les pages des 28 sets (jumelles), pour la jointure `intl` en
// bonus. Vérifiées en base le 2026-09-12 : Base-Set -> 1523 (211 produits, code BS), Base-Set-2 -> 1527.
// Elles ne comptent PAS dans la complétude, qui ne porte que sur le set cible.
const EXPANSIONS_INTL = {
    'Base Set': 1523,
    'Base Set 2': 1527
};

// ════════════════════════════════════════════════════════════════════════
// LES LIGNES AUTOMATIQUES — générées par generer-table-auto.js, 2026-09-14
// ════════════════════════════════════════════════════════════════════════
// 398 candidates (slug exact 253 · code de set 10 · page « (TCG) » 135 ; 5 sans slugSet écartées), chacune avec sa provenance
// dans `auto`. 🔴 UNE CANDIDATE N'ENTRE DANS `TABLE` QU'AVEC `verifie` — posé par
// `verifier-table.js --auto` sur des critères imprimés, jamais à la main. Tant qu'elle n'est pas
// vérifiée, `ligne(code)` la rend quand même : collecteur-texte.js dit alors POURQUOI il refuse,
// au lieu de répondre « absente de la table ».
// `TABLE_MAIN` : les lignes écrites à la main, seules lues par le générateur pour ne pas se relire.
const fs = require('fs');
const path = require('path');
const FICHIER_AUTO = path.join(__dirname, 'table-sets-auto.json');
const TABLE_AUTO = fs.existsSync(FICHIER_AUTO) ? JSON.parse(fs.readFileSync(FICHIER_AUTO, 'utf8')) : [];
const TABLE_MAIN = TABLE.slice();
TABLE.push(...TABLE_AUTO.filter(l => l.verifie));

// ════════════════════════════════════════════════════════════════════════
// LES LIGNES « SANS PAGE » — generer-table-sans-page.js, 2026-09-19
// ════════════════════════════════════════════════════════════════════════
// Des expansions Cardmarket qui n'ont AUCUNE page de set chez Bulbapedia — decks, coffrets, starter
// sets — mais dont les cartes déclarent l'expansion sur leurs propres pages, déjà collectées.
// L'énumération se retourne : au lieu de demander à un set ses cartes, on demande aux cartes leur set.
// Zéro requête, et la même jointure ensuite. Leur `verifie` est un contrôle MESURÉ EN BASE (part des
// numéros Cardmarket qui sont des numéros des impressions déclarées) ; sous le seuil, la ligne existe
// avec son motif de refus et ne collecte pas.
const FICHIER_SANS_PAGE = path.join(__dirname, 'table-sets-sans-page.json');
const TABLE_SANS_PAGE = fs.existsSync(FICHIER_SANS_PAGE) ? JSON.parse(fs.readFileSync(FICHIER_SANS_PAGE, 'utf8')) : [];
TABLE.push(...TABLE_SANS_PAGE.filter(l => l.verifie));

function ligne(code) {
    return TABLE.find(l => l.code === code) || TABLE_AUTO.find(l => l.code === code) || TABLE_SANS_PAGE.find(l => l.code === code) || null;
}

module.exports = { TABLE, TABLE_MAIN, TABLE_AUTO, TABLE_SANS_PAGE, FICHIER_AUTO, FICHIER_SANS_PAGE, EXPANSIONS_INTL, ligne };
