// ============================================================
// LES SETS QUE LES SOURCES TPC SERVENT — une ligne par (set, site, langue, code) ; ÉCRITE PAR CE QU'ELLE AUTORISE (§51)
// ============================================================
// Générée le 2026-10-07 (soir) depuis les MESURES de l'éditeur (« combien de nos trous chaque source comblerait »), zéro requête :
//   · TPC Asie : notre set rapproché d'un produit TPC par le CODE (un code ne se traduit pas, §39) — le code Cardmarket sans son suffixe
//     de langue (« SV-P/ID » → « SV-P ») ; la liste filtrée `expansionCodes=<code>` a rendu des cartes. Un set idth se lit en
//     INDONÉSIEN (le nom d'un Pokémon s'y écrit comme en anglais : la preuve par le nom y marche) ;
//   · pokemon-card.com : le paramètre `pg` que la page de recherche elle-même envoie ; un set dont la source rend plus de
//     2 × ses produits + 10 cartes est ÉCARTÉ (le code y désigne sans doute un autre produit : DPtP, 65 cartes pour 13 produits).
// Un set absent d'ici ne reçoit aucune unité TPC. Une ligne s'ajoute après une MESURE, jamais sur une supposition.
// `trous` : le compte du 2026-10-07, pour l'ordre de passage (plus gros d'abord) — jamais une promesse.
// `cartes` : le nombre de cartes que la liste filtrée a rendu ce jour-là. Le collecteur refuse une liste dont le total s'en écarte trop
// (moins de la moitié, plus du double + 20) : une source qui ignorerait son propre filtre rendrait des milliers de cartes d'autres sets.
// (Écrite par scratchpad/generer-tpc-sets.js ; `uniteDeLaLigne` est à la main : une régénération la recopie.)
const TABLE_TPC = Object.freeze([
    { slug: "Scarlet-Violet-Indonesian-Promos", site: "tpc-asie", langue: "id", code: "SV-P", tirage: "id", trous: 296, cartes: 251,
      mesure: "251 cartes chez TPC Asie id pour SV-P « Kartu Promo », 296 trous sur 296 produits (2026-10-07)" },
    { slug: "Sword-Shield-Indonesian-Promos", site: "tpc-asie", langue: "id", code: "S-P", tirage: "id", trous: 266, cartes: 320,
      mesure: "320 cartes chez TPC Asie id pour S-P « Kartu Promo », 266 trous sur 266 produits (2026-10-07)" },
    { slug: "M-P-Traditional-Chinese-Promos", site: "tpc-asie", langue: "tw", code: "M-P", tirage: "zh-hant", trous: 197, cartes: 208,
      mesure: "208 cartes chez TPC Asie tw pour M-P « 特典卡 超級進化 », 197 trous sur 197 produits (2026-10-07)" },
    { slug: "30th-Celebration-IDTH", site: "tpc-asie", langue: "id", code: "MA6", tirage: "idth", trous: 191, cartes: 199,
      mesure: "199 cartes chez TPC Asie id pour MA6 « Booster Pack \"30th CELEBRATION\" », 191 trous sur 191 produits (2026-10-07)" },
    { slug: "Scarlet-Violet-Thai-Promos", site: "tpc-asie", langue: "th", code: "SV-P", tirage: "th", trous: 173, cartes: 216,
      mesure: "216 cartes chez TPC Asie th pour SV-P « การ์ดโปรโม สการ์เล็ต แอนด์ ไวโอเล็ต », 173 trous sur 173 produits (2026-10-07)" },
    { slug: "Black-White-IDTH", site: "tpc-asie", langue: "id", code: "SV11s", tirage: "idth", trous: 172, cartes: 348,
      mesure: "348 cartes chez TPC Asie id pour SV11s « Booster Pack \"Hitam & Putih\" », 172 trous sur 172 produits (2026-10-07)" },
    { slug: "Sword-Shield-Thai-Promos", site: "tpc-asie", langue: "th", code: "S-P", tirage: "th", trous: 144, cartes: 132,
      mesure: "132 cartes chez TPC Asie th pour S-P « การ์ดโปรโม ซอร์ด แอนด์ ชีลด์ », 144 trous sur 144 produits (2026-10-07)" },
    { slug: "V-Starter-Decks", site: "pokemon-card-com", langue: "ja", code: "sD", tirage: "jp", trous: 127, cartes: 127,
      mesure: "127 cartes chez pokemon-card.com pour pg=sD, 127 trous sur 127 produits (2026-10-07)" },
    { slug: "M-P-Indonesian-Promos", site: "tpc-asie", langue: "id", code: "M-P", tirage: "id", trous: 126, cartes: 141,
      mesure: "141 cartes chez TPC Asie id pour M-P « Kartu Promo », 126 trous sur 126 produits (2026-10-07)" },
    { slug: "Space-Time-Creation", site: "pokemon-card-com", langue: "ja", code: "DP1", tirage: "jp", trous: 121, cartes: 124,
      mesure: "124 cartes chez pokemon-card.com pour pg=DP1, 121 trous sur 121 produits (2026-10-07)" },
    { slug: "Sword-Shield-Starter-Decks", site: "pokemon-card-com", langue: "ja", code: "sA", tirage: "jp", trous: 117, cartes: 122,
      mesure: "122 cartes chez pokemon-card.com pour pg=sA, 117 trous sur 117 produits (2026-10-07)" },
    { slug: "M-P-Thai-Promos", site: "tpc-asie", langue: "th", code: "M-P", tirage: "th", trous: 84, cartes: 135,
      mesure: "135 cartes chez TPC Asie th pour M-P « การ์ดโปรโม วิวัฒนาการเมก้า », 84 trous sur 84 produits (2026-10-07)" },
    { slug: "Shadow-Threat", site: "tpc-asie", langue: "id", code: "MA5", tirage: "idth", trous: 74, cartes: 238,
      mesure: "238 cartes chez TPC Asie id pour MA5 « Booster Pack \"Ancaman Bayangan\" », 74 trous sur 74 produits (2026-10-07)" },
    { slug: "Black-Sparkle", site: "tpc-asie", langue: "id", code: "SV3s", tirage: "id", trous: 63, cartes: 233,
      mesure: "233 cartes chez TPC Asie id pour SV3s « Booster Pack \"Kilau Hitam\" », 63 trous sur 63 produits (2026-10-07)" },
    { slug: "Transfiguration-Mask", site: "tpc-asie", langue: "id", code: "SV6s", tirage: "id", trous: 62, cartes: 229,
      mesure: "229 cartes chez TPC Asie id pour SV6s « Booster Pack \"Topeng Transfigurasi\" », 62 trous sur 62 produits (2026-10-07)" },
    { slug: "VMAX-Starter-Decks", site: "pokemon-card-com", langue: "ja", code: "sC", tirage: "jp", trous: 61, cartes: 20,
      mesure: "20 cartes chez pokemon-card.com pour pg=sC, 61 trous sur 61 produits (2026-10-07)" },
    { slug: "Sun-Moon-Starter-Set", site: "pokemon-card-com", langue: "ja", code: "smA", tirage: "jp", trous: 59, cartes: 68,
      mesure: "68 cartes chez pokemon-card.com pour pg=smA, 59 trous sur 59 produits (2026-10-07)" },
    { slug: "Paradox-Encounters", site: "tpc-asie", langue: "id", code: "SV4s", tirage: "id", trous: 58, cartes: 190,
      mesure: "190 cartes chez TPC Asie id pour SV4s « Pertemuan Paradoks », 58 trous sur 58 produits (2026-10-07)" },
    { slug: "Ace-Paradox", site: "tpc-asie", langue: "id", code: "SV5s", tirage: "id", trous: 58, cartes: 200,
      mesure: "200 cartes chez TPC Asie id pour SV5s « Booster Pack “Paradoks Andalan” », 58 trous sur 58 produits (2026-10-07)" },
    { slug: "Mega-Evolution-IDTH", site: "tpc-asie", langue: "id", code: "MA1", tirage: "idth", trous: 58, cartes: 184,
      mesure: "184 cartes chez TPC Asie id pour MA1 « Booster Pack \"Evolusi Mega\" », 58 trous sur 58 produits (2026-10-07)" },
    { slug: "Void-Blast", site: "tpc-asie", langue: "id", code: "MA4", tirage: "idth", trous: 58, cartes: 181,
      mesure: "181 cartes chez TPC Asie id pour MA4 « Booster Pack \"Ledakan Peniada\" », 58 trous sur 58 produits (2026-10-07)" },
    { slug: "Sword-Shield-Promos", site: "pokemon-card-com", langue: "ja", code: "S-P", tirage: "jp", trous: 53, cartes: 334,
      mesure: "334 cartes chez pokemon-card.com pour pg=S-P, 53 trous sur 347 produits (2026-10-07)" },
    { slug: "Presence-of-Champions", site: "tpc-asie", langue: "id", code: "SV10s", tirage: "idth", trous: 51, cartes: 189,
      mesure: "189 cartes chez TPC Asie id pour SV10s « Booster Pack \"Kehadiran Juara\" », 51 trous sur 51 produits (2026-10-07)" },
    { slug: "XY-Beginning-Set", site: "pokemon-card-com", langue: "ja", code: "HXY", tirage: "jp", trous: 49, cartes: 51,
      mesure: "51 cartes chez pokemon-card.com pour pg=HXY, 49 trous sur 49 produits (2026-10-07)" },
    { slug: "Beginning-Set-Pikachu", site: "pokemon-card-com", langue: "ja", code: "HSP", tirage: "jp", trous: 42, cartes: 19,
      mesure: "19 cartes chez pokemon-card.com pour pg=HSP, 42 trous sur 42 produits (2026-10-07)" },
    { slug: "Battle-Strength-Decks", site: "pokemon-card-com", langue: "ja", code: "BK", tirage: "jp", trous: 42, cartes: 11,
      mesure: "11 cartes chez pokemon-card.com pour pg=BK, 42 trous sur 42 produits (2026-10-07)" },
    { slug: "Entry-Pack-08", site: "pokemon-card-com", langue: "ja", code: "EP08", tirage: "jp", trous: 42, cartes: 43,
      mesure: "43 cartes chez pokemon-card.com pour pg=EP08, 42 trous sur 42 produits (2026-10-07)" },
    { slug: "Indigo-Flame", site: "tpc-asie", langue: "id", code: "MA2", tirage: "idth", trous: 40, cartes: 143,
      mesure: "143 cartes chez TPC Asie id pour MA2 « Booster Pack \"Kobaran Biru\" », 40 trous sur 40 produits (2026-10-07)" },
    { slug: "MEGA-Start-Deck-100-Battle-Collection", site: "pokemon-card-com", langue: "ja", code: "mC", tirage: "jp", trous: 40, cartes: 774,
      mesure: "774 cartes chez pokemon-card.com pour pg=mC, 40 trous sur 766 produits (2026-10-07)" },
    { slug: "Sun-Moon-Family-Pokemon-Card-Game", site: "pokemon-card-com", langue: "ja", code: "smL", tirage: "jp", trous: 38, cartes: 69,
      mesure: "69 cartes chez pokemon-card.com pour pg=smL, 38 trous sur 51 produits (2026-10-07)" },
    { slug: "Eevee-GX-Starter-Sets", site: "pokemon-card-com", langue: "ja", code: "smI", tirage: "jp", trous: 38, cartes: 38,
      mesure: "38 cartes chez pokemon-card.com pour pg=smI, 38 trous sur 38 produits (2026-10-07)" },
    { slug: "World-Championships-2023-Yokohama-Deck-Pikachu", site: "pokemon-card-com", langue: "ja", code: "WCS23", tirage: "jp", trous: 30, cartes: 32,
      mesure: "32 cartes chez pokemon-card.com pour pg=WCS23, 30 trous sur 30 produits (2026-10-07)" },
    { slug: "ex-Starter-Set-Fuecoco-Ampharos-ex", site: "pokemon-card-com", langue: "ja", code: "svAL", tirage: "jp", trous: 24, cartes: 24,
      mesure: "24 cartes chez pokemon-card.com pour pg=svAL, 24 trous sur 24 produits (2026-10-07)" },
    { slug: "MEGA-Starter-Set-Zorua-Zoroark-ex", site: "pokemon-card-com", langue: "ja", code: "mEZ", tirage: "jp", trous: 20, cartes: 20,
      mesure: "20 cartes chez pokemon-card.com pour pg=mEZ, 20 trous sur 20 produits (2026-10-07)" },
    { slug: "MEGA-Starter-Set-Sprigatito-Meowscarada-ex", site: "pokemon-card-com", langue: "ja", code: "mEM", tirage: "jp", trous: 18, cartes: 18,
      mesure: "18 cartes chez pokemon-card.com pour pg=mEM, 18 trous sur 18 produits (2026-10-07)" },
    { slug: "Melee-Pokemon-Scramble", site: "pokemon-card-com", langue: "ja", code: "MPS", tirage: "jp", trous: 16, cartes: 11,
      mesure: "11 cartes chez pokemon-card.com pour pg=MPS, 16 trous sur 16 produits (2026-10-07)" },
    { slug: "Garchomp-Half-Deck", site: "pokemon-card-com", langue: "ja", code: "GBR", tirage: "jp", trous: 15, cartes: 18,
      mesure: "18 cartes chez pokemon-card.com pour pg=GBR, 15 trous sur 15 produits (2026-10-07)" },
    { slug: "V-UNION-Special-Card-Sets", site: "pokemon-card-com", langue: "ja", code: "sp5", tirage: "jp", trous: 13, cartes: 4,
      mesure: "4 cartes chez pokemon-card.com pour pg=sp5, 13 trous sur 13 produits (2026-10-07)" },
    { slug: "Tag-Team-GX-Premium-Trainer-Box", site: "pokemon-card-com", langue: "ja", code: "smJ", tirage: "jp", trous: 10, cartes: 35,
      mesure: "35 cartes chez pokemon-card.com pour pg=smJ, 10 trous sur 35 produits (2026-10-07)" },
    { slug: "Terastal-Starter-Set-Skeledirge-ex", site: "pokemon-card-com", langue: "ja", code: "svEL", tirage: "jp", trous: 7, cartes: 22,
      mesure: "22 cartes chez pokemon-card.com pour pg=svEL, 7 trous sur 22 produits (2026-10-07)" },
    { slug: "Stellar-Guidance", site: "tpc-asie", langue: "id", code: "SV7s", tirage: "idth", trous: 6, cartes: 172,
      mesure: "172 cartes chez TPC Asie id pour SV7s « Bimbingan Rasi », 6 trous sur 63 produits (2026-10-07)" },
    { slug: "VMAX-Climax", site: "pokemon-card-com", langue: "ja", code: "s8b", tirage: "jp", trous: 6, cartes: 279,
      mesure: "279 cartes chez pokemon-card.com pour pg=s8b, 6 trous sur 284 produits (2026-10-07)" },
    { slug: "Sword-Shield-Starter-Set-Lucario-VSTAR", site: "pokemon-card-com", langue: "ja", code: "sLL", tirage: "jp", trous: 6, cartes: 22,
      mesure: "22 cartes chez pokemon-card.com pour pg=sLL, 6 trous sur 21 produits (2026-10-07)" },
    { slug: "Ultra-Sun-Ultra-Moon-Deck-Build-Boxes", site: "pokemon-card-com", langue: "ja", code: "smG", tirage: "jp", trous: 5, cartes: 12,
      mesure: "12 cartes chez pokemon-card.com pour pg=smG, 5 trous sur 17 produits (2026-10-07)" },
    { slug: "Scarlet-Violet-ex-Special-Set", site: "pokemon-card-com", langue: "ja", code: "svP1", tirage: "jp", trous: 5, cartes: 7,
      mesure: "7 cartes chez pokemon-card.com pour pg=svP1, 5 trous sur 7 produits (2026-10-07)" },
    { slug: "Shiny-Treasure-ex", site: "pokemon-card-com", langue: "ja", code: "sv4a", tirage: "jp", trous: 4, cartes: 360,
      mesure: "360 cartes chez pokemon-card.com pour pg=sv4a, 4 trous sur 359 produits (2026-10-07)" },
    { slug: "25th-Anniversary-Collection", site: "pokemon-card-com", langue: "ja", code: "s8a", tirage: "jp", trous: 4, cartes: 34,
      mesure: "34 cartes chez pokemon-card.com pour pg=s8a, 4 trous sur 38 produits (2026-10-07)" },
    { slug: "Scarlet-Violet-Promos", site: "pokemon-card-com", langue: "ja", code: "SV-P", tirage: "jp", trous: 4, cartes: 332,
      mesure: "332 cartes chez pokemon-card.com pour pg=SV-P, 4 trous sur 257 produits (2026-10-07)" },
    { slug: "Wild-Blaze", site: "pokemon-card-com", langue: "ja", code: "XY2", tirage: "jp", trous: 3, cartes: 87,
      mesure: "87 cartes chez pokemon-card.com pour pg=XY2, 3 trous sur 90 produits (2026-10-07)" },
    { slug: "Fusion-Arts", site: "pokemon-card-com", langue: "ja", code: "s8", tirage: "jp", trous: 2, cartes: 115,
      mesure: "115 cartes chez pokemon-card.com pour pg=s8, 2 trous sur 129 produits (2026-10-07)" },
    { slug: "Rising-Fist", site: "pokemon-card-com", langue: "ja", code: "XY3", tirage: "jp", trous: 2, cartes: 103,
      mesure: "103 cartes chez pokemon-card.com pour pg=XY3, 2 trous sur 105 produits (2026-10-07)" },
    { slug: "Phantom-Gate", site: "pokemon-card-com", langue: "ja", code: "XY4", tirage: "jp", trous: 2, cartes: 95,
      mesure: "95 cartes chez pokemon-card.com pour pg=XY4, 2 trous sur 97 produits (2026-10-07)" },
    { slug: "Bandit-Ring", site: "pokemon-card-com", langue: "ja", code: "XY7", tirage: "jp", trous: 2, cartes: 11,
      mesure: "11 cartes chez pokemon-card.com pour pg=XY7, 2 trous sur 97 produits (2026-10-07)" },
    { slug: "Emerald-Break", site: "pokemon-card-com", langue: "ja", code: "XY6", tirage: "jp", trous: 2, cartes: 11,
      mesure: "11 cartes chez pokemon-card.com pour pg=XY6, 2 trous sur 91 produits (2026-10-07)" },
    { slug: "Tag-Team-GX-Deck-Build-Box", site: "pokemon-card-com", langue: "ja", code: "smN", tirage: "jp", trous: 2, cartes: 29,
      mesure: "29 cartes chez pokemon-card.com pour pg=smN, 2 trous sur 29 produits (2026-10-07)" },
    { slug: "Terastal-Starter-Set-Mewtwo-ex", site: "pokemon-card-com", langue: "ja", code: "svEM", tirage: "jp", trous: 2, cartes: 22,
      mesure: "22 cartes chez pokemon-card.com pour pg=svEM, 2 trous sur 22 produits (2026-10-07)" },
    { slug: "M-P-Promos", site: "pokemon-card-com", langue: "ja", code: "M-P", tirage: "jp", trous: 2, cartes: 156,
      mesure: "156 cartes chez pokemon-card.com pour pg=M-P, 2 trous sur 135 produits (2026-10-07)" },
    { slug: "Starter-Set-ex-Stevens-Beldum-Metagross-ex", site: "pokemon-card-com", langue: "ja", code: "svOD", tirage: "jp", trous: 2, cartes: 19,
      mesure: "19 cartes chez pokemon-card.com pour pg=svOD, 2 trous sur 21 produits (2026-10-07)" },
    { slug: "Starter-Set-ex-Marnies-Morpeko-Grimmsnarl-ex", site: "pokemon-card-com", langue: "ja", code: "svOM", tirage: "jp", trous: 2, cartes: 20,
      mesure: "20 cartes chez pokemon-card.com pour pg=svOM, 2 trous sur 21 produits (2026-10-07)" },
    { slug: "Secret-of-the-Lakes", site: "pokemon-card-com", langue: "ja", code: "DP2", tirage: "jp", trous: 1, cartes: 145,
      mesure: "145 cartes chez pokemon-card.com pour pg=DP2, 1 trous sur 123 produits (2026-10-07)" },
    { slug: "Tag-Bolt", site: "pokemon-card-com", langue: "ja", code: "sm9", tirage: "jp", trous: 1, cartes: 109,
      mesure: "109 cartes chez pokemon-card.com pour pg=sm9, 1 trous sur 118 produits (2026-10-07)" },
    { slug: "Shining-Darkness", site: "pokemon-card-com", langue: "ja", code: "DP3", tirage: "jp", trous: 1, cartes: 146,
      mesure: "146 cartes chez pokemon-card.com pour pg=DP3, 1 trous sur 109 produits (2026-10-07)" },
    { slug: "Double-Blaze", site: "pokemon-card-com", langue: "ja", code: "sm10", tirage: "jp", trous: 1, cartes: 107,
      mesure: "107 cartes chez pokemon-card.com pour pg=sm10, 1 trous sur 115 produits (2026-10-07)" },
    { slug: "World-Champions-Pack", site: "pokemon-card-com", langue: "ja", code: "WCP", tirage: "jp", trous: 1, cartes: 108,
      mesure: "108 cartes chez pokemon-card.com pour pg=WCP, 1 trous sur 108 produits (2026-10-07)" },
    { slug: "Silver-Lance", site: "pokemon-card-com", langue: "ja", code: "s6h", tirage: "jp", trous: 1, cartes: 83,
      mesure: "83 cartes chez pokemon-card.com pour pg=s6h, 1 trous sur 95 produits (2026-10-07)" },
    { slug: "Fairy-Rise", site: "pokemon-card-com", langue: "ja", code: "sm7b", tirage: "jp", trous: 1, cartes: 56,
      mesure: "56 cartes chez pokemon-card.com pour pg=sm7b, 1 trous sur 63 produits (2026-10-07)" },
    { slug: "Forbidden-Light-JP", site: "pokemon-card-com", langue: "ja", code: "sm6", tirage: "jp", trous: 1, cartes: 102,
      mesure: "102 cartes chez pokemon-card.com pour pg=sm6, 1 trous sur 110 produits (2026-10-07)" },
    { slug: "Start-Deck-100-CoroCoro-Comic-Version", site: "pokemon-card-com", langue: "ja", code: "sN", tirage: "jp", trous: 1, cartes: 25,
      mesure: "25 cartes chez pokemon-card.com pour pg=sN, 1 trous sur 24 produits (2026-10-07)" },
    { slug: "30th-Celebration-Premium-Deck-Set", site: "pokemon-card-com", langue: "ja", code: "mF", tirage: "jp", trous: 1, cartes: 49,
      mesure: "49 cartes chez pokemon-card.com pour pg=mF, 1 trous sur 44 produits (2026-10-07)" },
    { slug: "ex-Starter-Set-Pikachu-ex-Pawmot", site: "pokemon-card-com", langue: "ja", code: "svC", tirage: "jp", trous: 1, cartes: 24,
      mesure: "24 cartes chez pokemon-card.com pour pg=svC, 1 trous sur 24 produits (2026-10-07)" }
]);
const ligneTpc = (site, slug) => TABLE_TPC.find(l => l.site === site && l.slug === slug) || null;
/** L'unité de file d'une ligne — la forme que l'alimentateur insère et que la garde du collecteur (`releve`) accepte, mot pour mot. */
const uniteDeLaLigne = L => ({ _id: `${L.site}/${L.slug}`, source: L.site, slugSet: L.slug, code: L.code, langue: L.langue, trous: L.trous });
module.exports = { TABLE_TPC, ligneTpc, uniteDeLaLigne };
